(declare-const a Int)
(declare-const b Int)
(declare-const c Int)
(declare-const out Int)
(declare-fun f (Int Bool) Int)
(assert (= a 10))
(assert (= b 10))
(assert (= out 21))
(assert ( = c (+ a b)))
(assert (= c out))
(check-sat)